_core:
  default_config_hash: l23AWlsVwlhblRhggKqahd8SBZzQDs5_GsFuCKgDItg
exclude_paths: "/contextual/*\r\n/toolbar/*\r\n/edit/*\r\n*.js\r\n*.css"
intercept_redirects: false
purge_on_cache_clear: true
active_toolbar_items:
  ajax: ajax
  assets: assets
  blocks: blocks
  cache: cache
  config: config
  database: database
  devel: devel
  events: events
  extensions: extensions
  forms: forms
  frontend: frontend
  http: http
  mail: mail
  memory: memory
  request: request
  routing: routing
  services: services
  state: state
  theme: theme
  time: time
  translations: translations
  user: user
  views: views
query_sort: source
query_highlight: 5
ide: 'phpstorm://open?file=%f&line=%l'
ide_remote_path: ''
ide_local_path: ''
