<?php

/**
 * @file
 * Provides a mb entity entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\mb_entity\Entity\MbEntity;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function mb_entity_theme() {
  return [
    'mb_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for mb entity templates.
 *
 * Default template: mb-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the mb entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_mb_entity(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function mb_entity_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish mb entities.
      $storage = \Drupal::entityTypeManager()->getStorage('mb_entity');
      $mb_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($mb_entity_ids) as $mb_entity) {
        $mb_entity->set('status', FALSE);
        $mb_entity->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize mb entities.
      $storage = \Drupal::entityTypeManager()->getStorage('mb_entity');
      $mb_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($mb_entity_ids) as $mb_entity) {
        $mb_entity->setOwnerId(0);
        $mb_entity->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function mb_entity_user_predelete(UserInterface $account) {
  // Delete mb entities.
  $storage = \Drupal::entityTypeManager()->getStorage('mb_entity');
  $mb_entity_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $mb_entities = $storage->loadMultiple($mb_entity_ids);
  $storage->delete($mb_entities);
  // Delete old revisions.
  $mb_entity_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->execute();
  foreach (array_keys($mb_entity_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}
