druframe_offer.druframe_offer_type.*:
  type: config_entity
  label: 'DruFrame Offer type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
